Repository Netcracker/qubership-integration-catalog-library, pull requests merged in 2025-01, with the labels that each got.

#5 Release with patch label
  README.md
Labels: bug, feature

#6 Remove deprecated GitHub Actions workflows for release management
  .github/workflows/github-release.yaml
  .github/workflows/publish-on-release-tag.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-to-maven-central.yaml
Labels: enhancement

#8 Refactored mapper configuration
  src/main/java/org/qubership/integration/platform/catalog/configuration/MapperBaseConfiguration.java
  src/main/java/org/qubership/integration/platform/catalog/consul/ConsulService.java
  src/main/java/org/qubership/integration/platform/catalog/service/EnvironmentBaseService.java
  src/main/java/org/qubership/integration/platform/catalog/service/exportimport/ProtocolExtractionService.java
  src/main/java/org/qubership/integration/platform/catalog/service/exportimport/SpecificationImportService.java
  src/main/java/org/qubership/integration/platform/catalog/service/parsers/ParserUtils.java
  src/main/java/org/qubership/integration/platform/catalog/service/parsers/impl/AsyncapiSpecificationParser.java
  src/main/java/org/qubership/integration/platform/catalog/service/parsers/impl/GraphqlSpecificationParser.java
  src/main/java/org/qubership/integration/platform/catalog/service/parsers/impl/ProtobufSpecificationParser.java
Labels: feature
